### PR TITLE
Make compatible with kitspace.org

### PR DESCRIPTION
**Pull request by kasbah**
Hey, neat soundcard! 

Thought this would be a nice project for [kitspace.org](https://kitspace.org). Kitspace aims to make it easier for others to replicate projects. In your case the documentation is already superb so it doesn't add too much but it doesn't hurt to put it up either. You do get 1-click links to order the parts which is slightly easier than before. 

To make it compaitble I:

1. Unzipped the gerber files
2. Added a `kitspace.yaml` manifest file to tell Kitspace which files are which

### CODE REVIEW

**Comment by kasbah** [comment]
Oh almost forgot, here is a preview of what it will look like: http://add-snark-barker.preview.kitspace.org/boards/github.com/kitspace-forks/snark-barker/

**Comment by kasbah** [comment]
Ping @schlae, not interested? Should I close this PR?

**Comment by schlae** [comment]
No thanks.

**Comment by kasbah** [comment]
Fair enough. Can I ask why? Could we do anything to improve Kitspace so someone like you would want to mirror your project there?

**Pull request closed without merging**
